---
title: "salt_runs"
output: html_document
---
```{r}
library(tidyverse)
library(readxl)
library(ggthemes)
library(ggforce)
library(RColorBrewer)
library(SciViews)
library(FSA)

```



```{r}
raw1 <- read_excel("./salt_runs/salt_1_and_2_deux.xlsx", 2) %>%
  select(-c(...91))

#raw2<- read_excel("./salt_runs/salt_1_and_2.xlsx", 2) %>%
#  select(-c(...91))

raw3<- read_excel("./salt_runs/salt_3_and_4.xlsx", 2) %>%
  select(-c(...91))

raw4<- read_excel("./salt_runs/salt_5_and_6.xlsx", 2) %>%
  select(-c(...91))

raw5<- read_excel("./salt_runs/salt_5_and_7.xlsx", 2) %>%
  select(-c(...91))

raw6<- read_excel("./salt_runs/salt_6_and_8.xlsx", 2) %>%
  select(-c(...91))
```

```{r}

make_the_thing <- function(df) {
pull_sides <- df %>% select(-contains("Blank")) %>%
  select(-contains("Ctrl")) %>%
  select(-contains("A0")) %>% #Remove A rows 
  select(-contains("A1")) %>%
  select(-contains("H0")) %>% #Remove H rows 
  select(-contains("H1"))
 
pull_sides[pull_sides<0] <- 0
pull_sides <- pull_sides %>% rename(
  reading = "Reading",
  time = "avg. time [s]")


names(pull_sides)[3:62] <- str_sub(names(pull_sides)[3:62],end = -11)

pivot <- pull_sides %>% pivot_longer(cols = -c(reading, time), names_to = "strain", values_to = "od")

pivot  <- pivot[!is.na(pivot$reading),]

clean <- pivot %>% group_by(reading, time, strain) %>%
  summarise_if(is.numeric, mean) %>%   
  ungroup() %>%
  mutate(time = time / 3600,
         tag = 1:4340) %>%
  rename(name = strain)

return(clean)

}


split_the_names <- function(df){
split_names <- str_split_fixed(df$name, "\\%", 2)  %>% 
  as_tibble() %>%
  mutate(tag = 1:4340) %>% #total counts
  rename(salt = "V1",
         strain = "V2")

add_names <- left_join(df, split_names) %>%
  select(c(-name, -tag))

return(add_names)

}

stderr <- function(x) sd(x)/sqrt(length(x))

```

```{r}
make_1 <- make_the_thing(raw1) %>% split_the_names()

#make_2 <- make_the_thing(raw2)  %>% split_the_names()

make_3 <- make_the_thing(raw3)  %>% split_the_names()

make_4 <- make_the_thing(raw4)  %>% split_the_names()

make_5 <- make_the_thing(raw5)  %>% split_the_names()

make_6 <- make_the_thing(raw6)  %>% split_the_names()



make_all_the_things <- rbind(make_1, make_3, make_4, make_5, make_6) %>%
  mutate(strain = recode(strain,
                         "ATC" = "ATCC"))

make_all_the_things  <- make_all_the_things[!is.na(make_all_the_things$time),]

ave_time <- make_all_the_things %>%
  select(-c(od, strain, salt))%>%
  group_by(reading) %>%
  summarize_if(is.numeric, mean) %>%
  ungroup()

fix_time <- make_all_the_things %>%
  select(-time) %>%
  left_join(ave_time)

clean_salt <- fix_time %>% 
  group_by(reading, time, strain, salt) %>%
  mutate(standard_error = stderr(od),
         max_od = od + standard_error,
         min_od = od - standard_error) %>%
  summarize_if(is.numeric, mean) %>%
  ungroup() %>%
  mutate(salt = recode(salt,
                       "1" = "1%",
                       "2" = "2%",
                       "3" = "3%",
                       "4" = "4%",
                       "5" = "5%",
                       "6" = "6%",
                       "7" = "7%",
                       "8" = "8%"))

```

```{r}
write.csv(fix_time, "all_salt.csv")
```


```{r, fig.width =10}
cols = c("#66C2A5", "#FC8D62", "#8DA0CB", "#E78AC3", "#A6D854", "#FFD92F", "#E5C494", "#B3B3B3")

p_salt <- clean_salt %>% ggplot() +
  geom_line(aes(x = time, y = od, color = strain), size =1) +
  facet_wrap(~salt) +
  theme_bw() +
  xlab("Time (hrs)")+
  ylab("Optical Density (600nm)")+
  labs(color = "Strain") +
  ggtitle("V. alginolyticus strains vs. salt content")+
    scale_color_manual(values = cols)


p_salt


```


```{r}
only_551 <- clean_salt %>% subset(strain == "551")

only_507 <- clean_salt %>% subset(strain == "507")

only_580 <- clean_salt %>% subset(strain == "580")

only_ATCC <- clean_salt %>% subset(strain == "ATCC")

```

```{r}
only_551 %>% ggplot() +
  geom_line(aes(x = time, y = od, color = salt), size =1) +
  theme_bw() +
  xlab("Time (hrs)")+
  ylab("Optical Density (600nm)")+
  labs(color = "Strain") +
  ggtitle("V. alginolyticus strain 551 vs. salt content")+
    scale_color_manual(values = cols)

only_580 %>% ggplot() +
  geom_line(aes(x = time, y = od, color = salt), size =1) +
  theme_bw() +
  xlab("Time (hrs)")+
  ylab("Optical Density (600nm)")+
  labs(color = "Strain") +
  ggtitle("V. alginolyticus strain 580 vs. salt content")+
    scale_color_manual(values = cols)

only_507 %>% ggplot() +
  geom_line(aes(x = time, y = od, color = salt), size =1) +
  theme_bw() +
  xlab("Time (hrs)")+
  ylab("Optical Density (600nm)")+
  labs(color = "Strain") +
  ggtitle("V. alginolyticus strain 507 vs. salt content")+
    scale_color_manual(values = cols)

only_ATCC %>% ggplot() +
  geom_line(aes(x = time, y = od, color = salt), size =1) +
  theme_bw() +
  xlab("Time (hrs)")+
  ylab("Optical Density (600nm)")+
  labs(color = "Strain") +
  ggtitle("V. alginolyticus strain ATCC vs. salt content")+
    scale_color_manual(values = cols)
```


```{r, fig.width=10}
lag_phase <- clean_salt %>% subset(od >= 0.05 & od < 0.15)
stat_phase <- clean_salt %>% subset(time >= 14.5 & od < 15.5)
cols = c("#66C2A5", "#FC8D62", "#8DA0CB", "#E78AC3", "#A6D854", "#FFD92F", "#E5C494", "#B3B3B3")

just_ave_lag <- lag_phase %>% select(salt, time, strain) %>%
  group_by(salt, strain) %>%
  mutate(lag_error = stderr(time),
         lag_n = n()) %>%
  summarize_if(is.numeric, mean) %>%
  ungroup() %>%
  rename(lag_time = time) %>%
  mutate(max_lag = lag_time + lag_error,
         min_lag = lag_time - lag_error)


```


```{r}
#T-test lag
test <- lag_phase %>% subset(strain == "580" & salt == "3%")
t1 <- test$time
test2 <- lag_phase %>% subset(strain == "580" & salt == "4%")
t2 <- test2$time
test3 <- lag_phase %>% subset(strain == "ATCC" & salt == "1%")
t3 <- test3$time

wilcox.test(t1, t2)

print("551")
o_551 <- lag_phase %>% subset(strain == "551")

pairwise.wilcox.test(o_551$time, o_551$salt, p.adjust.method = "bonferroni")

print("580")

o_580 <- lag_phase %>% subset(strain == "580")

pairwise.wilcox.test(o_580$time, o_580$salt, p.adjust.method = "bonferroni")

print("ATCC")
o_atcc <- lag_phase %>% subset(strain == "ATCC")

pairwise.wilcox.test(o_atcc$time, o_atcc$salt, p.adjust.method = "bonferroni")

```







```{r}
clean_salt <- clean_salt %>% left_join(just_ave_lag)
clean_salt$strain <- factor(clean_salt$strain, levels = c("551", "580", "507", "ATCC"))
```


```{r}
#serious GR equation
library(SciViews)
x <- clean_salt %>% select(-standard_error, -max_od, -min_od) %>%
  subset(od >= 0.1 & od <= 0.75) %>%
  select(-lag_time)

x$reading <- as.numeric(as.character(x$reading))
x <- x[!(x$reading < 50), ]

binned <- x %>% group_by(strain, salt) %>%
  mutate(total_hits = n()) %>%
  ungroup() %>%
  mutate(total_min = total_hits*2.3,
         reading_min = reading * 2.3)


early_log <- binned %>% select(-total_hits, -total_min, -reading, -time) %>%
  subset(od <= 0.2) %>%
  group_by(strain, salt) %>%
  mutate(early_od_err = stderr(od),
         early_time_err = stderr(reading_min)) %>%
  summarize_if(is.numeric, mean) %>%
  ungroup() %>%
  rename(early_log_od = od, 
         early_log_min = reading_min) %>%
  mutate(early_od_max = early_log_od + early_od_err,
         early_od_min = early_log_od - early_od_err,
         early_time_max = early_log_min + early_time_err,
         early_time_min = early_log_min - early_time_err)

late_log <- binned %>% select(-total_hits, -total_min, -reading, -time) %>%
  subset(od > 0.65) %>%
  group_by(strain, salt) %>%
  mutate(late_od_err = stderr(od),
         late_time_err = stderr(reading_min)) %>%
  summarize_if(is.numeric, mean) %>%
  ungroup() %>%
  rename(late_log_od = od,
         late_log_min = reading_min) %>%
    mutate(late_od_max = late_log_od + late_od_err,
         late_od_min = late_log_od - late_od_err,
         late_time_max = late_log_min + late_time_err,
         late_time_min = late_log_min - late_time_err)

gr_df <- left_join(early_log, late_log)

gr_df <- gr_df %>% mutate(time_diff = late_log_min - early_log_min) %>%
  mutate(ln_late_log = ln(late_log_od)) %>%
  mutate(ln_early_log = ln(early_log_od)) %>%
  mutate(gr_constant = ((ln_late_log) - (ln_early_log)) / time_diff) %>%
  mutate(gr = 0.6931 / gr_constant)

gr_df_max <- gr_df %>% mutate(time_diff_max = late_time_max - early_time_max) %>%
  mutate(ln_late_log_max = ln(late_od_max)) %>%
  mutate(ln_early_log_max = ln(early_od_max)) %>%
  mutate(gr_constant_max = ((ln_late_log_max) - (ln_early_log_max)) / time_diff_max) %>%
  mutate(gr_max = 0.6931 / gr_constant_max)  %>%
  select(strain, salt, gr_max)

gr_df_min <- gr_df %>% mutate(time_diff_min = late_time_min - early_time_min) %>%
  mutate(ln_late_log_min = ln(late_od_min)) %>%
  mutate(ln_early_log_min = ln(early_od_min)) %>%
  mutate(gr_constant_min = ((ln_late_log_min) - (ln_early_log_min)) / time_diff_min) %>%
  mutate(gr_min = 0.6931 / gr_constant_min) %>%
  select(strain, salt, gr_min)

gr_df_prime <- gr_df %>% left_join(gr_df_max) %>% 
  left_join(gr_df_min) %>%
  select(strain, salt, gr, gr_max, gr_min) %>%
  left_join(just_ave_lag) %>%
  select(-lag_error)

#gr_df %>% ggplot() +
#  geom_line(aes(x = salt, y = gr, color = strain, group = strain))
```

```{r, fig.width =10}
cols = c("#66C2A5", "#FC8D62", "#8DA0CB", "#E78AC3", "#A6D854", "#FFD92F", "#E5C494", "#B3B3B3")


```


```{r}

dont_make_507 <- clean_salt[!(clean_salt$strain == "507"), ]

p_salt_2 <- dont_make_507 %>% ggplot() +
  geom_line(aes(x = time, y = od, color = strain), size =1) +
  facet_wrap(~salt) +
  theme_bw() +
  xlab("Time (hrs)")+
  ylab("Optical Density (600nm)")+
  labs(color = "Strain") +
  #ggtitle("V. alginolyticus strains vs. salt content")+
    scale_color_manual(values = cols)+
  scale_y_continuous(breaks = seq(0, 1.7, 0.5), limits = c(0, 1.7))


p_salt_2


```

```{r}

minus_507 <- gr_df_prime[!(gr_df$strain == "507"), ]

use <- minus_507 

use1 <- use %>% select(-strain) %>%
  group_by(salt) %>%
  mutate(gr_error = stderr(gr),
         lag_error = stderr((lag_time))) %>%
  summarize_if(is.numeric, mean) %>%
  ungroup() %>%
  mutate(max_gr = gr + gr_error,
         min_gr = gr - gr_error,
         max_lag = lag_time + lag_error,
         min_lag =lag_time - lag_error) %>%
  mutate(tag = "dude")


```

```{r}
smooth <- use %>% select(-strain) %>%
  group_by(salt) %>%
  #summarize_if(is.numeric, mean, na.rm = TRUE)%>%
  mutate(strain = "ave")
```


```{r, fig.width=6}

p1 <- use %>% ggplot() +
  geom_point(aes(x = salt, y = gr, color = strain)) +
  geom_line(aes(x = salt, y = gr, group = strain, color = strain)) +
 # geom_smooth(data = smooth, aes(x = salt, y = gr, group = strain), color = "grey", size = 1)+
 # geom_point(data = smooth, aes(x = salt, y = gr, group = strain), color = "black", size = 1)+
  geom_errorbar(aes(x = salt, ymax = gr_max, ymin = gr_min, color = strain), width = 0.5) +
  scale_fill_manual(values = cols) +
  theme_bw() +
  xlab("Salinity (%)") +
  ylab("Doubling Time (min)")+
  labs(color = "Strain")+
    geom_vline(xintercept = 2, linetype = "dashed", color = "black")+
  geom_vline(xintercept = 4, linetype = "dashed", color = "black")

p1

p2<- use %>% ggplot() +
  geom_point(aes(x = salt, y = lag_time, color = strain)) +
  geom_line(aes(x = salt, y = lag_time, group = strain, color = strain)) +
    #geom_smooth(data = smooth, aes(x = salt, y = lag_time, group = strain), color = "grey", size = 1)+
  geom_errorbar(aes(x = salt, ymax = max_lag, ymin = min_lag, color = strain), width = 0.5) +
  scale_fill_manual(values = cols) +
  theme_bw() +
  xlab("Salinity (%)") +
  ylab("Duration of Lag Time (hrs)")+
  labs(color = "Strain")+
  geom_vline(xintercept = 2, linetype = "dashed", color = "black")+
  geom_vline(xintercept = 4, linetype = "dashed", color = "black")


p2

#ggarrange(p1, p2, ncol = 1)
```
```{r}
saveRDS(use, "./salt_FINAL.rds")
```


```{r}
library(writexl)
t <- readRDS("./temp_FINAL.rds")
write_xlsx(t,"./temp_FINAL.xlsx")

s <- readRDS("./salt_FINAL.rds")
write_xlsx(s, "./salt_FINAL.xlsx")

i <- readRDS("./iron_FINAL.rds")
write_xlsx(i, "./iron_FINAL.xlsx")

```


```{r, fig.height=7, fig.width=6}

library(ggpubr)
ggarrange(p1, p2, ncol = 1, align = "hv")
```


```{r}

print("551")
lag_551 <- lag_phase %>% subset(strain == "551")
shapiro.test(lag_551$time)
kruskal.test(time ~ salt, data = lag_551)
dunnTest(lag_551$time ~ lag_551$salt, method = "holm")
```


```{r}
print("580")
lag_580 <- lag_phase %>% subset(strain == "580")
shapiro.test(lag_580$time)
kruskal.test(time ~ salt, data = lag_580)
dunnTest(lag_580$time ~ lag_580$salt, method = "holm")

```


```{R}
print("ATCC")
lag_atcc <- lag_phase %>% subset(strain == "ATCC")
shapiro.test(lag_atcc$time)
kruskal.test(time ~ salt, data = lag_atcc)
dunnTest(lag_atcc$time ~ lag_atcc$salt, method = "holm")
```


```{r}
early_log_range <- binned %>% select(-total_hits, -total_min, -reading, -time) %>%
  subset(od <= 0.2) %>%
  rename(early_log_od = od, 
         early_log_min = reading_min)

late_log_range <- binned %>% select(-total_hits, -total_min, -reading, -time) %>%
  subset(od > 0.65) %>%
  rename(late_log_od = od,
         late_log_min = reading_min) 

gr_df_range <- left_join(early_log_range, late_log_range)

gr_df_all_range <- gr_df_range %>% mutate(time_diff = late_log_min - early_log_min) %>%
  mutate(ln_late_log = ln(late_log_od)) %>%
  mutate(ln_early_log = ln(early_log_od)) %>%
  mutate(gr_constant = ((ln_late_log) - (ln_early_log)) / time_diff) %>%
  mutate(gr = 0.6931 / gr_constant) %>%
  select(strain, salt, gr)

gr_551 <- gr_df_all_range %>% subset(strain == "551") %>% na.omit()

```


```{r}
print("551")

gr_551 <- gr_df_all_range %>% subset(strain == "551") %>% na.omit()
shapiro.test(gr_551$gr)
kruskal.test(gr ~ salt, data = gr_551)
dunnTest(gr_551$gr ~ gr_551$salt, method = "holm")
```

```{r}
print("580")

gr_580 <- gr_df_all_range %>% subset(strain == "580") %>% na.omit()
shapiro.test(gr_580$gr)
kruskal.test(gr ~ salt, data = gr_580)
dunnTest(gr_580$gr ~ gr_580$salt, method = "holm")
```

```{r}
print("ATCC")

gr_atcc <- gr_df_all_range %>% subset(strain == "ATCC") %>% na.omit()
shapiro.test(gr_atcc$gr)
kruskal.test(gr ~ salt, data = gr_atcc)
dunnTest(gr_atcc$gr ~ gr_atcc$salt, method = "holm")
```





