---
title: "artemia_dose_quantification"
output: html_document
---



```{r}
library(tidyverse)
library(readxl)
library(xgxr)
```

```{r}
raw <- read_excel("./artemia_dose_data.xlsx", 2) %>%
  mutate(perc_of_dose_aquired2 = total_cfu_in_artemia/average_cfu_in_50ul_dose*100)
```

paste(italic('p value')

```{r}
clean <- raw %>% mutate(species = recode(species,
                                         "alginolyticus" = "V. alginolyticus",
                                         "harveyi" = "V. harveyi",
                                         "medi" = "V. mediterranei"))
```

```{r}
clean %>% ggplot() +
  geom_boxplot(aes(x = species, y = total_cfu_in_artemia, fill = species))+
  scale_y_log10() +
  theme_bw() +
  theme(legend.position = "none") +
  xlab("Species")+
  ylab("Total CFU")
```

```{r}
clean %>% ggplot() +
  geom_boxplot(aes(x = species, y = perc_of_dose_aquired, fill = species))+
  scale_y_log10() +
  theme_bw() +
  theme(legend.position = "none") +
  xlab("Species")+
  ylab("CFU/")
```

```{r}
stderr <- function(x) sd(x)/sqrt(length(x))


ave_dose <- clean %>% select(species, total_cfu_in_artemia, average_cfu_in_50ul_dose) %>%
  pivot_longer(cols = -c(species), names_to = "cfu_designation", values_to = "total_cfu_in_artemia") %>%
  group_by(species, cfu_designation) %>%
  mutate(serror = stderr(total_cfu_in_artemia)) %>%
  summarise_if(is.numeric, mean) %>%
  ungroup() %>%
  mutate(cfu_designation = recode(cfu_designation,
                                   "total_cfu_in_artemia" = "Acquired by Artemia",
                                   "average_cfu_in_50ul_dose" = "Initial Dose")) %>%
  mutate(ymax = total_cfu_in_artemia + serror,
         ymin = total_cfu_in_artemia - serror)


```


```{r}
ave_dose$cfu_designation <- factor(ave_dose$cfu_designation, levels = c("Initial Dose", "Acquired by Artemia"))

ave_dose %>% ggplot()+
  geom_bar(aes(x=species, y = total_cfu_in_artemia, fill = cfu_designation), stat = "identity", 
           position = position_dodge())+
  geom_errorbar(aes(x = species, ymax = ymax, ymin = ymin, fill = cfu_designation), 
           width = 0.4, position = position_dodge(0.9))+
  #geom_text(aes(x = species, y = total_cfu_in_artemia, fill = cfu_designation, 
   #             label = round(total_cfu_in_artemia, 2)), position = position_dodge())+
 #scale_y_log10(
#   breaks = scales::trans_breaks("log10", function(x) 10^x),
#   labels = scales::trans_format("log10", scales::math_format(10^.x)))+
  theme_bw()+
  ylab("Average CFU")+
  xlab("Species") +
  labs(fill = "Vibrio spp.\nConcentration")


```

