---
title: "EPA_Analayis_Sala_Lab"
output: html_document
---

```{r}
library(tidyverse)
library(readxl)
library(ggthemes)
library(fuzzyjoin)
library(data.table)
library(writexl)
```



```{r}
vip_liver <- read_excel("./Final Peak Table for RJV Sala Lab Study_for figures by BN.xlsx", 3) %>%
  select(-Details) %>%
  mutate(label = "VIP Liver")
vip_swab <- read_excel("./Final Peak Table for RJV Sala Lab Study_for figures by BN.xlsx", 4) %>%
  select(-Details) %>%
  mutate(label = "VIP Swab")
liver_cpf <- read_excel("./Final Peak Table for RJV Sala Lab Study_for figures by BN.xlsx", 5) %>%
  select(-Details) %>%
  mutate(label = "Liver CPF")
swab_cpf <- read_excel("./Final Peak Table for RJV Sala Lab Study_for figures by BN.xlsx", 6) %>%
  select(-Details) %>%
  mutate(label = "Swab CPF")
liver_24d <- read_excel("./Final Peak Table for RJV Sala Lab Study_for figures by BN.xlsx", 7) %>%
  select(-Details) %>%
  mutate(label = "Liver 2,4-D")
swab_24d <- read_excel("./Final Peak Table for RJV Sala Lab Study_for figures by BN.xlsx", 8) %>%
  select(-Details) %>%
  mutate(label = "Swab 2,4-D")

smpdb_names <- read_excel("./Final Peak Table for RJV Sala Lab Study_for figures by BN.xlsx", 10) 
raw_names <- read_excel("./Final Peak Table for RJV Sala Lab Study_for figures by BN.xlsx", 9) %>%
  left_join(smpdb_names)


combine_all <- rbind(vip_liver, vip_swab, liver_24d, swab_24d, liver_cpf, swab_cpf)  %>%
  rename(pathway_name = metabolite_set) %>%
  left_join(raw_names)


combine_all$label <- factor(combine_all$label, levels = c("VIP Liver", "VIP Swab", "Liver CPF", "Swab CPF", "Liver 2,4-D", "Swab 2,4-D"))

#pathways <- raw_path %>% left_join(raw_names)

```
```{r}
combine_all <- combine_all %>% mutate(range = total_metabolites-1) %>%
  mutate(norm_val = (hits - 1)/range)
```



```{r, fig.width=12, fig.height=12}
combine_all %>% ggplot() +
  geom_tile(aes(x = label, y = pathway_name, fill = hits), 
            color = "black", width = 0.75)+
  geom_text(aes(x = label, y = pathway_name, 
                label = paste0(hits, "/", total_metabolites), fill = hits), color ="black", size = 3)+
facet_grid(sub_pathway ~ ., scales="free_y", space = "free_y")+
scale_fill_gradient(low = "white", high = "firebrick3") +
  xlab("Sample Type") +
  ylab("Pathway Name") +
  labs(fill = "Pathway Hits")+
  theme_hc()+
   ylab("")+
   xlab("")+
   theme(strip.placement = "outside",
         strip.text.y.right = element_text(angle = 0, size = 9),
         strip.background = element_rect(color = "black"),
        axis.text.y = element_text(size = 9),
         axis.text.x = element_text(size = 11.5)) 


combine_all %>% ggplot() +
  geom_tile(aes(x = label, y = pathway_name, fill = norm_val), 
            color = "black", width = 0.75)+
  geom_text(aes(x = label, y = pathway_name, 
                label = round(norm_val,3), fill = norm_val), color ="black", size = 3)+
facet_grid(sub_pathway ~ ., scales="free_y", space = "free_y")+
scale_fill_gradient(low = "white", high = "firebrick3") +
  xlab("Sample Type") +
  ylab("Pathway Name") +
  labs(fill = "Pathway Hits")+
  theme_hc()+
   ylab("")+
   xlab("")+
   theme(strip.placement = "outside",
         strip.text.y.right = element_text(angle = 0, size = 9),
         strip.background = element_rect(color = "black"),
        axis.text.y = element_text(size = 9),
         axis.text.x = element_text(size = 11.5)) 
```

```{r, fig.width=10, fig.height=10}

combine_all %>% ggplot() +
  geom_tile(aes(x = label, y = pathway_name, fill = hits), 
            color = "black", width = 0.75)+
  geom_text(aes(x = label, y = pathway_name, 
                label = paste0(hits, "/", total_metabolites), fill = hits), color ="black", size = 3.5)+
#facet_grid(sub_pathway ~ ., scales="free_y", space = "free_y")+
scale_fill_gradient(low = "white", high = "firebrick3") +
  xlab("Sample Type") +
  ylab("Pathway Name") +
  labs(fill = "Pathway Hits")+
  theme_hc()
```

```{r}
# #library(ggcorrplot)
# model.matrix(~0+., data=combine_all) %>% 
#   cor(use="pairwise.complete.obs") %>% 
#   ggcorrplot(show.diag = T, type="lower", lab=F, lab_size=1.5)+
#   theme(axis.text.x = element_text(size = 6.5, angle = 90, vjust = 0.5),
#         axis.text.y = element_text(size = 6.5))
# 
# 
# library(corrplot)
# cor.table = cor(combine_all)
# corrplot(cor.table)
```



